### ISSUE TITLE
error while getting datasets with "git annex get"

### ISSUE THREAD

**Issue by mmallad** [commonsense/conceptnet-numberbatch#38]
I have done all setup and tried to get dataset with git annex command but it says 

get code/source-data/conceptnet5.5.csv 
  Remote origin not usable by git-annex; setting annex-ignore
(not available) 
  No other repository is known to contain the file.
failed
get code/source-data/conceptnet5.csv (not available) 
  No other repository is known to contain the file.
failed
get code/source-data/ensemble-2016-03.300d.npy (not available) 
  No other repository is known to contain the file.
failed
get code/source-data/ensemble-2016-03.600d.npy (not available) 
  No other repository is known to contain the file.
failed
get code/source-data/ensemble-2016-03.labels (not available) 
  No other repository is known to contain the file.
failed
get code/source-data/glove.42B.300d.txt (not available) 
  No other repository is known to contain the file.
failed
get code/source-data/glove12.840B.300d.txt (not available) 
  No other repository is known to contain the file.
failed
get code/source-data/ppdb-xl-lexical.csv (not available) 
  No other repository is known to contain the file.
failed
get code/source-data/w2v-google-news.bin.gz (not available) 
  No other repository is known to contain the file.
failed
git-annex: get: 9 failed

**Comment by rspeer** [comment]
Sorry! I was cleaning up old branches, and thought `git-annex` was a feature branch from when I introduced git-annex, but actually it's the branch where `git-annex` keeps all its information about where to find files.

I've restored the branch and it should work now. But man, I am not using this inscrutable, haphazardly-documented utility again.

**Comment by mmallad** [comment]
Thank you for reply. I downloaded all dataset by my self. I fixed some format issues and now its running all okay. I would like to ask some questions about it can you please provide your email address.
Thank You

**Comment by jatin270** [comment]
Hey can you tell me how you downloaded the datasets

**Comment by rspeer** [comment]
@jatin270 Can you be more specific about what you're looking for?

Currently, all parts of ConceptNet, including Numberbatch, are built using the code in https://github.com/commonsense/conceptnet5. Its build script will download the input data from Zenodo: https://zenodo.org/record/998169

**Comment by jatin270** [comment]
@rspeer can you tell me format of conceptnet5.csv file like in what way have they stored the data?

**Comment by rspeer** [comment]
I'm really going to need you to be more specific what you're asking about, but is this what you're looking for? https://github.com/commonsense/conceptnet5/wiki/Downloads

**Comment by jatin270** [comment]
@rspeer 
get source-data/w2v-google-news.bin.gz (from web...) 

  Unable to access these remotes: web

  Try making some of these repositories available:
  	00000000-0000-0000-0000-000000000001 -- web
   	2feaff51-0a4a-4afc-8b56-b9a553161e49 -- rspeer@buffy:~/conceptnet-retrofitting-paper
   	54f3fff2-290c-42f1-908f-a6b2c9785668 -- media-lab-rsync
   	7ffdd42d-dce8-4cb8-904e-d09097500dfa -- rspeer@ip-10-23-1-47:~/conceptnet-retrofitting-paper
   	91510204-049b-4033-a6cf-0fe419754978 -- mungojerrie 2.7TB HD
   	dd2f35a5-4cde-4d3b-a6a1-69167174aea0 -- rspeer@buffy:/home/rspeer/conceptnet-retrofitting-paper

  (Note that these git remotes have annex-ignore set: origin)
failed

I am obtaining this error

**Comment by tukeyclothespin** [comment]
I have the same 'git annex get' issue as @jatin270 and @mmallad.

**Comment by rspeer** [comment]
@tukeyclothespin, could you tell me where you encountered the directions to use git annex? Those directions are very old and I need to get rid of things that point to them.

The built data in .csv format is available from https://github.com/commonsense/conceptnet5/wiki/Downloads, and the raw input data is hosted at https://zenodo.org/record/1165009.

Unlike git-annex, Zenodo is very well suited for long-term data hosting.

**Comment by rspeer** [comment]
Ah, no, the .csv.gz file was in response to what @jatin270 was looking for.

I can look for the files that are inputs to the 2016 paper, but probably nothing I do will save git-annex from the bit rot that's seemingly designed into it.

I'm supposing you went with the 2016 paper because the instructions for reproducing the AAAI 2017 paper using Docker were too daunting? I'm working on the process, on making it possible to build ConceptNet Numberbatch without all the sysadminnery, but it's going to be a newer (better) version, not an exact replication.

**Comment by tukeyclothespin** [comment]
Yes, I went with the 2016 paper and branch 16.04 because the instructions were more approachable, I don't need the web api features from Conceptnet, and I can run docker but not docker compose on my infrastructure. I am going to try the raw build instructions at https://github.com/commonsense/conceptnet5/wiki/Build-process. 

Beyond that, I am open to building and running any version of ConceptNet-Numberbatch. My goal is to add my pretrained word embedding models of specialized vocabulary into the ConceptNet-Numberbatch build and evaluate the word embedding results via our own use case metric that we already have defined. I just need access to the terms and vectors output by ConceptNet-Numberbatch to see how they score on our metric. That's why the simplicity of the branch 16.04 instructions was appealing.

**Comment by rspeer** [comment]
I'll work on updating the documentation. I've put the data files you need up on Zenodo: https://zenodo.org/record/1208722

Download these files and put them in your `source-data` directory, and you should be able to run the 16.04 build.

Note that this is for reproducing the paper, and the distinct feature of this paper compared to the others is that we tried various combinations of data sources and parameters. The build process, as described, will build all of them.

**Comment by rspeer** [comment]
The modern build process is described at: https://github.com/commonsense/conceptnet5/wiki/Build-process

**Comment by tukeyclothespin** [comment]
Thanks for your patience, I really appreciate it. I downloaded the data files from your link, put them into the source-data directory of my 16.04 version, ran python ninja.py and then sudo ninja but get a segfault nearly immediately. I am going to take a break from looking at that because I was separately able to work through the build process using the current conceptnet5 package.

I noticed your comment in the google group to run install the dependencies and run 
`snakemake data/vectors/numberbatch.h5` 
to build the Numberbatch vectors. That worked and I was able to load the Numberbatch vectors in gensim! 

Now I want to add my own pretrained word embeddings into Numberbatch this time so I put a gzipped file of the word2vec text format of my model terms/vectors in data/raw/vectors. During snakemake I saw:

rule convert_word2vec:
    input: data/raw/vectors/GoogleNews-vectors-negative300.bin.gz
    output: data/vectors/w2v-google-news.h5
    jobid: 14
    resources: ram=24

But I never saw snakemake run convert_word2vec on the word2vec gz file I had in data/raw/vectors. The initial job list also stated that there was only one job for convert_word2vec. Do I need to add my new file name in a conceptnet configuration script? I noticed the four other input embeddings are mentioned in the Snakefile:
`INPUT_EMBEDDINGS = [
    'crawl-300d-2M', 'w2v-google-news', 'glove12-840B', 'fasttext-opensubtitles'
]`

**Comment by tukeyclothespin** [comment]
I think I have it:
1) Put the term/vector output file in data/raw/vectors/
1) Make a new rule in the snakefile with the input as my file in data/raw/vectors/ and the output as a h5 file name in data/vectors
2) Add the name of the h5 file output from the new rule to the INPUT_EMBEDDINGS list
3) snakemake clean
4) snakemake data/vectors/numberbatch.h5
